config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  get '/google4d9e386ef35cdb35', to: 'pages#google4d9e386ef35cdb35'

  resources :stores

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :stores, only: [:index, :show]
    end
  end

  resources :search, only: [:index]
  resources :profiles, only: [:index]
end

app/controllers/profiles_controller.rb
require 'json'
require 'open-uri'

class ProfilesController < ApplicationController
  def index
    @magasins = Store.where(user: current_user)
    @stores = policy_scope(Store)

    url = 'https://api.coinmarketcap.com/v1/ticker/?limit=2'
    url_cryptos = open(url).read
    @cryptos = JSON.parse(url_cryptos)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/index.html.erb
<div class="wrapper-profil">
  <div class="header-title">
    <h1>Hello <em><%= current_user.name %></em> !</h1>
  </div>
  <div class="btn-section">
    <div class="btn-add">
      <%= link_to 'Ajouter mon commerce', new_store_path, class: "btn-override" %>
    </div>
    <div class="btn-profil">
      <%= link_to 'Modifier mon profil', edit_user_registration_path, class: 'btn-override-profil' %>
    </div>
  </div>
  <div class="profil-store-content">
    <ul class='list-inline'>
      <% @magasins.each do |store| %>
        <li>
          <div class="profil-store-content-img">
            <%= cl_image_tag store.photo, height: 220, width: 280, crop: :fill %>
          </div>
          <div class="profil-store-content-title">
            <h4>
              <%= link_to store.name, store_path(store)%>
            </h4>
          </div>
          <div class="profil-store-content-edit">
            <% if policy(store).update? %>
              <%= link_to edit_store_path(store) do %>
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              <% end %>
            <% end %>
            <% if policy(store).destroy? %>
              <%= link_to store_path(store),
                    method: :delete,
                    data: { confirm: "Veux-tu vraiment supprimer ce magasin ?" } do %>
                <i class="fa fa-trash-o" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>