config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  get '/google4d9e386ef35cdb35', to: 'pages#google4d9e386ef35cdb35'

  resources :stores

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :stores, only: [:index, :show]
    end
  end

  resources :search, only: [:index]
  resources :profiles, only: [:index]
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user

  validates :name, uniqueness: true, presence: true
  validates :category, presence: true
  validates :postcode, presence: true
  validates :address, uniqueness: true, presence: true
  validates :crypto, presence: true
  validates :slug, presence: true, uniqueness: true


  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch
  pg_search_scope :search, against: [:name,
                                     :category,
                                     :address,
                                     :postcode,
                                     :crypto,
                                     :description],
  using: {
        tsearch: { prefix: true } # <-- now `superman batm` will return something!
      }

  mount_uploader :photo, PhotoUploader

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/api/v1/stores_controller.rb
class Api::V1::StoresController < Api::V1::BaseController
  before_action :set_restaurant, only: [ :show ]

  def index
    @stores = policy_scope(Store)
  end

  def show
  end

  private

  def set_restaurant
    @store = Store.find(params[:id])
    authorize @store  # For Pundit
  end
end

app/controllers/stores_controller.rb
require 'json'
require 'open-uri'

class StoresController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_store, only: [:edit, :update, :destroy]
  before_action :set_cryptos

  def index
    @stores = policy_scope(Store).order(created_at: :desc)
    @stores2 = Store.where.not(latitude: nil, longitude: nil)

        @markers = @stores2.map do |store|
          {
            lat: store.latitude,
            lng: store.longitude,
            infoWindow: { content: '<a href="/stores/' + store.id.to_s + '">' + store.name + '</a><br/>' +
                                   store.category +
                                   '<br>' +
                                   store.address
            }
          }
        end
  end

  def show
    @store = Store.friendly.find(params[:id])
    authorize @store
    @store_user = @store.user_id
    @user = User.find(@store_user)
  end


  def new
    @store = Store.new
    authorize @store
  end

  def create
    @store = Store.new(store_params)
    authorize @store
    @store.user = current_user
    if @store.save
      redirect_to store_path(@store)
    else
      render :new
    end

  end

  def edit
  end

  def update
    @store.update(store_params)
    redirect_to store_path(@store)
  end

  def destroy
    @store.destroy
    redirect_to profiles_path
  end

  private

  def set_cryptos
    url = 'https://api.coinmarketcap.com/v1/ticker/?limit=2'
    url_cryptos = open(url).read
    @cryptos = JSON.parse(url_cryptos)
  end

  def set_store
    @store = Store.friendly.find(params[:id])
    authorize @store
  end

  def store_params
    params.require(:store).permit(:name,
                                  :category,
                                  :description,
                                  :address,
                                  :postcode,
                                  :opening_hours,
                                  :crypto,
                                  :contact,
                                  :website,
                                  :slug,
                                  :photo)
  end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= simple_form_for(@store) do |f| %>
  <%= f.input :name, label: 'Le nom de votre commerce'%>
  <%= f.input :category, label: 'Categorie', selected: [ "Bar" ], collection: [ "Bar", "Restaurant", "Hotel", "Coworking", "Soins", "Autres"] %>
  <%= f.input :description %>
  <%= f.input :address, label: 'Adresse', id: "store_address" %>
  <%= f.input :postcode, label: 'Arrondissement', collection: 75001..75020, selected: 75001 %>
  <%= f.input :opening_hours, label: "Heures d'ouvertures" %>
  <%= f.input :crypto, label: "Vous acceptez quelle(s) cryptomonnaie(s) ?" %>
  <%= f.input :contact, label: "Téléphone ou email" %>
  <%= f.input :website, label: "Site internet" %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit, class: "btn btn-primary", value: "Valider"  %>
<% end %>

app/views/stores/edit.html.erb
<div class="wrapper-form-stores">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <h1>Mise à jour de votre boutique</h1>
        <%= render 'form' %>
  <!-- url_for(:back) récupère l'url visitée avant le form -->
        <%= link_to 'Retour', url_for(:back) %>
      </div>
    </div>
  </div>
</div>

app/views/stores/index.html.erb
<div class="page-search">
  <div class="top-search-container">
    <div class="navbar-search text-center">
      <ul class="list-btn" id="list-inline-override">
        <li id="btn-bars">
          <p class="list-hover">
            <%= link_to 'Bars', "/search?utf8=%E2%9C%93&categorie=bar" %>
          </p>
        </li>
        <li class="btn-list">
          <p class="list-hover">
            <%= link_to 'Restaurants', '/search?utf8=%E2%9C%93&categorie=restaurant' %>
          </p>
        </li>
        <li class="btn-list">
          <p class="list-hover">
            <%= link_to 'Hotels', '/search?utf8=%E2%9C%93&categorie=hotel' %>
          </p>
        </li>
        <li class="btn-list">
          <p class="list-hover">
            <%= link_to 'Coworking', '/search?utf8=%E2%9C%93&categorie=coworking' %>
          </p>
        </li>
        <li class="btn-list">
          <p class="list-hover">
            <%= link_to 'Soins', '/search?utf8=%E2%9C%93&categorie=soins' %>
          </p>
        </li>
        <li class="btn-list">
          <p class="list-hover">
            <%= link_to 'Autres', '/search?utf8=%E2%9C%93&categorie=autres' %>
          </p>
        </li>
      </ul>
    </div>
    <div class="header-search">
      <div class="search-bar">
        <div class="search-icon">
          <i class="fa fa-search" aria-hidden="true"></i>
        </div>
        <div class="search-input">
          <%= form_tag(search_index_path, method: "get") do %>
            <%= text_field_tag :query, nil, placeholder: 'ex: 34 rue du Caire, Paris', class: "input-search", id: "store_address" %>
        </div>
        <div class="search-btn">
            <%= submit_tag "Chercher", class: "btn-search" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="container wrapper-map-stores">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div
          id="map"
          style="width: 100%;
          height: 400px;"
          data-markers="<%= @markers.to_json %>"
        ></div>
      </div>
    </div>
  </div>

  <div class="container cards-search">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div id="stores">
          <% @stores.each do |store| %>
            <%= link_to store_path(store) do %>
              <div class="product">
                <%= cl_image_tag store.photo, height: 100, width: 200, crop: :fill, class: "product-image hidden-xs" %>
                <div class='product-body'>
                  <h3><%= link_to store.name, store_path(store) %></h3>
                  <p><%= store.category %> | <%= store.crypto %></p>
                </div>
                <ul class="list-inline product-controls hidden-sm hidden-xs">
                  <li><%= store.address %></li>
                  <li><%= store.postcode %></li>
                </ul>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stores/new.html.erb
<div class="wrapper-form-stores">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <h1>Ajoutez votre boutique</h1>
        <%= render 'form' %>
        <!-- url_for(:back) récupère l'url visitée avant le form -->
        <%= link_to 'Retour', url_for(:back) %>
      </div>
    </div>
  </div>
</div>

app/views/stores/show.html.erb
<div class="wrapper-show">
  <div class="header">
    <div class="back">
      <p><%= link_to 'Retour', url_for(:back) %></p>
    </div>
    <div class="header-title">
      <h1><%= @store.name %></h1>
    </div>
    <div class="header-content">
      <div class="header-category">
        <p>/<%= @store.category %></p>
      </div>
      <div class="header-address">
        <p><i class="fa fa-map-marker" aria-hidden="true"></i>
        <%= @store.address %> <%= @store.postcode %></p>
      </div>
      <div class="header-website">
        <p><%= link_to @store.website, @store.website, target: "_blank" %></p>
      </div>
      <div class="header-edit-delete">
        <% if user_signed_in? %>
          <p>
            <% if policy(@store).update? %>
              <%= link_to edit_store_path do %>
                <i class="fa fa-pencil-square-o icon-edit" aria-hidden="true"></i>
              <% end %>
            <% end %>
            <% if policy(@store).destroy? %>
              <%= link_to store_path(@store),
                    method: :delete,
                    data: { confirm: "Veux-tu vraiment supprimer ce magasin ?" } do %>
                <i class="fa fa-trash-o icon-delete" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </p>
        <% end %>
      </div>
    </div>
  </div>


  <div class="section">
    <div class="store-content">
      <div class="store-img-header text-center">
        <%= cl_image_tag @store.photo, height: 220, width: 280, crop: :fill %>
      </div>
      <div class="store-infos">
        <div class="store-infos-crypto">
          <p><i class="fa fa-btc" aria-hidden="true"></i>
          <%= @store.crypto %></p>
        </div>
        <div class="store-infos-hours">
          <p><i class="fa fa-clock-o" aria-hidden="true"></i>
          <%= @store.opening_hours %></p>
        </div>
          <p><i class="fa fa-user" aria-hidden="true"></i>
          <%= @store.contact %></p>
        <div class="store-description">
          <p><%= @store.description %></p>
          <p>Ajouté par <em><%= @user.name %></em></p>
        </div>
      </div>
    </div>
  </div>
</div>