config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  get '/google4d9e386ef35cdb35', to: 'pages#google4d9e386ef35cdb35'

  resources :stores

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :stores, only: [:index, :show]
    end
  end

  resources :search, only: [:index]
  resources :profiles, only: [:index]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-content">
  <div class="footer-left">
  <ul>
    <li><strong>A PROPOS</strong></li>
    <li><p>Coin de Paris, vous permet de trouver tous les
    commerces à Paris qui acceptent le paiement en cryptomonnaie.
    Bitcoin, Ethereum, etc. </p></li>
  </ul>
  </div>
  <div class="footer-middle">
    <ul>
      <li><strong>RECHERCHER</strong></li>
      <li><%= link_to 'Bars', "search?utf8=%E2%9C%93&categorie=bar" %></li>
      <li><%= link_to 'Restaurants', 'search?utf8=%E2%9C%93&categorie=restaurant' %></li>
      <li><%= link_to 'Hotels', 'search?utf8=%E2%9C%93&categorie=hotel' %></li>
      <li><%= link_to 'Coworking', 'search?utf8=%E2%9C%93&categorie=coworking' %></li>
      <li><%= link_to 'Soins', 'search?utf8=%E2%9C%93&categorie=soins' %></li>
      <li><%= link_to 'Autres', 'search?utf8=%E2%9C%93&categorie=autres' %></li>
    </ul>
  </div>
  <div class="footer-right">
    <ul>
      <li><strong>INFOS</strong></li>
      <li><%= link_to 'Api', api_v1_stores_path, target: "_blank" %></li>
      <li><%= link_to 'Contact', pages_contact_path %></li>
    </ul>
  </div>
  <div class="footer-partnerships">
    <strong>PARTENAIRES</strong>
    <ul>
      <li>
        <%= link_to "https://courscryptomonnaies.com/", target: '_blank' do %>
        <%= image_tag 'logo-courscrypto.png' %>
        <% end %>
      </li>
      <li>
        <%= link_to "https://bitcoin.fr/", target: '_blank' do %>
        <%= image_tag 'bitcoinfr.png' %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_google_analytics.html.erb
<% if Rails.env == "production"  %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-113316431-1">
  </script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-113316431-1');
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag 'logo.png' %>
  </a>
  <div class="cryptos">
    <ul>
      <% @cryptos.each do |crypto| %>
        <div class="crypto">
          <li>
            <ul class=list-crypto>
              <li>
                <strong><%= crypto['name'] %></strong>
              </li>
              <% if (crypto['percent_change_1h'].to_i < 0) %>
                <li>
                  <i class="fas flash fa-long-arrow-alt-down"></i>
                </li>
                <li>
                  <%= crypto['percent_change_1h'] %>%
                </li>
                <li>
                  <strong>
                    <%= ((crypto['price_usd'].to_i)*0.801102317).round(2) %>€
                  </strong>
                </li>
              <% else %>
              <li>
                <i class="fas flash fa-long-arrow-alt-up"></i>
              </li>
              <li>
                <%= crypto['percent_change_1h'] %>%
              </li>
              <li>
                <strong>
                  <%= ((crypto['price_usd'].to_i)*0.801102317).round(2) %>€
                </strong>
              </li>
              <% end %>
            </ul>
          </li>
        </div>
      <% end %>
    </ul>
  </div>
  <% if user_signed_in? %>
  <!-- Navbar right -->
    <div class="connection">
      <p>
        <%= link_to 'Accueil', root_path %>
      </p>
      <p>
        <%= link_to 'Rechercher', stores_path %>
      </p>
      <p>
        <%= link_to 'Mon profil', profiles_path %>
      </p>
      <p>
        <%= link_to 'Deconnexion', destroy_user_session_path, method: :delete, class: "dropdown-itstrong" %>
      </p>
    </div>
</div>

  <% else %>
  <!-- Login link (when logged out) -->
    <div class="connection">
      <p>
        <%= link_to 'Accueil', root_path %>
      </p>
      <p>
        <%= link_to 'Commerces', stores_path %>
      </p>
      <p>
        <%= link_to "Connexion", new_user_session_path %>
      </p>
    </div>
  <% end %>
</div>